FROM apache/airflow:2.9.1

USER root
RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /requirements.txt
# python -m pip contourne le wrapper root de l'image officielle
RUN python -m pip install --no-cache-dir -r /requirements.txt
